### ISSUE TITLE
Logon issue (PC and Windows Mobile)

### ISSUE THREAD

**Issue by fqbhla** [owncloud/OwncloudUniversal#22]
Hi..

Just got my server running (with self-signed-certificat). Installed the app on both PC and phone and I get the same error on both 
![owncloud](https://user-images.githubusercontent.com/42057798/43629122-a5e9305e-96fc-11e8-889f-44471618f392.JPG) 
![wp_ss_20180803_0001](https://user-images.githubusercontent.com/42057798/43629165-d0b6ca3a-96fc-11e8-9d48-4645ae6150f9.png)

meaning that it's not even possible to login.
Everything works great in a browser and with the normal desktop client.

Bo Larsen

**Comment by pestotoast** [comment]
Yes, self signed certificates don't work with the version that is currently available in the store. The are 3 possible solutions at this time:

1. Install Let's Encrypt on your server to get a valid certificate
2. Export your self signed certificate on your PC (with Chrome or Firefox) into a *.p7b file, copy it on your phone an install it. Do the same on your PC but make sure you install it as a 'Trusted Root Certificate Authority'.
3. Try out the preview version of the app which has support for self-signed certificates (this version is not yet available via the windows store). Unfortunately side-loading apps is not very user friendly. You can download the latest version of the app [here](https://ci.appveyor.com/project/DeepDiver1975/ownclouduniversal/build/artifacts) and follow the installation instruction from [here](https://github.com/owncloud/OwncloudUniversal/releases) but using the files you downloaded before.

Sorry, I haven't had time to release the new version (with the fix for your problem) yet. But I will probably be able to finish it within the next weeks.

**Comment by fqbhla** [comment]
Hi Adrian…

Thank you! The sideload worked like a charm and everything Works great!

I did build the server on a Raspberry Pi 3B+ with a nice 2TB disk connected – and it runs very wel.

Venlig hilsen

Bo H. Larsen
---
Født fri - skattet ihjel

________________________________
Fra: Adrian Gebhart <notifications@github.com>
Sendt: Friday, August 3, 2018 6:45:10 PM
Til: owncloud/OwncloudUniversal
Cc: fqbhla; Author
Emne: Re: [owncloud/OwncloudUniversal] Logon issue (PC and Windows Mobile) (#22)


Yes, self signed certificates don't work with the version that is currently available in the store. The are 3 way to fix this at this time:

  1.  Install Let's Encrypt on your server to get a valid certificate
  2.  Export your self signed certificate on your PC into a *.p7b file, copy it on your phone an install it. Do the same on your PC but make sure you install it as a 'Trusted Root Certificate Authority'.
  3.  Try out the preview version of the app which has support for self-signed certificates (this version is not yet available via the windows store). Unfortunately side-loading apps is not very user friendly. You can download the latest version of the app here<https://ci.appveyor.com/project/DeepDiver1975/ownclouduniversal/build/artifacts> and follow the installation instruction from here<https://github.com/owncloud/OwncloudUniversal/releases> but using the files you downloaded before.

Sorry, I haven't had time to release the new version (with the fix for your problem) yet. But I will probably be able to finish it within the next weeks.

**Comment by fqbhla** [comment]
Hi..

Used option 3 and it works like a charm :-) Thank you.

Regards

Bo Larsen
