### ISSUE TITLE
Automatic Synchronisation(Settingspage) Error on enabling Backgroundtask

### ISSUE THREAD

**Issue by ghost** [owncloud/OwncloudUniversal#23]
Hi Everyone,

I,m using the Universal Owncloud Desktop/Mobile version on Windows 10(Desktop) and i,m expeirence an error if i on the settingspage enable the function "Automatic Synchronisation" the option Background task the error message are: Ooops there occur an error restart the app and try again.
I;m therefore unable to open modify or share my files.

![schermopname 61](https://user-images.githubusercontent.com/19804873/44519566-aa45ae80-a6cd-11e8-9062-5827660983bb.png)

**Comment by michaelstingl** [comment]
@gvanosch12 For production, we recommend to use the regular desktop sync client:
https://owncloud.org/download/#owncloud-desktop-client

**Comment by ghost** [comment]
Wy not updating the windows 10 app from the store?
I would like to use the windows 10 app

**Comment by michaelstingl** [comment]
@gvanosch12 this what the description in the Microsoft store says:

> For an optimal experience on the PC, please consider using the normal desktop sync client instead. You can find it here: https://owncloud.org/install/#install-clients 

(see: https://www.microsoft.com/en-us/p/owncloud/9pj6d2hkq1zt)

FYI @pestotoast is working on the universal Win 10 app in his free time. Here you can support him: https://paypal.me/pestotoast

**Comment by pestotoast** [comment]
@gvanosch12 For synchronization on PC's the desktop client is recommended (as @michaelstingl already said) for the following reasons:
- it's the official client for PCs so it has more developers and better support
- synchronization faster and more reliable
- changes are synced instantly (the app will only sync every 30 minutes)
and many other reasons.

If you have a Windows 10 Mobile phone you can use this app for synchronization.

Because of this the Windows 10 app informs you after login about the desktop sync client and how to download it (unless you click 'Do not show again').

The Windows 10 app will never be as fast and reliable as the desktop sync client because Windows 10 apps are more limited in what they can do (compared to traditional desktop applications).

You can use the Windows 10 app as a client on your PC to view your photos and videos/upload/download your files manually (especially if you have a tablet-pc), but to synchronize files you better use the [desktop client](https://owncloud.org/download/#owncloud-desktop-client), as the application itself says.

However, it would be nice if you would submit a diagnostic report, so I can check the logs of the app (then I can try to find the reason of the error). Go to Settings -> About -> Send diagnostic report.

Edit: just received your mail, will answer you there too

**Comment by pestotoast** [comment]
Closing this (after some clarification via email). The user is connecting to an unsupported server.
